---
apiVersion: v1
kind: Pod
metadata:
  name: preveil-web-app
  app: preveil-web-app
spec:
  containers:
    - image: aydave/prevail-web:latest
      name: preveil-web-app
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 5000